import git
from git_contributions_importer import *


repo = git.Repo("P:/JIraBitBucket/ecos-scrape")
mock_repo = git.Repo("P:/FreeLance/mock-repo")

importer = Importer([repo], mock_repo)
importer.set_author("amine.a.belgaid@gmail.com")

importer.import_repository()
print("iducx")
print("toeoy")
print("gxcjs")
print("fevad")
print("wrcni")
print("hkimc")
print("mblgf")
print("adfiv")
print("osvxb")
print("qolru")
print("yyawq")
print("unmxm")
print("hwsty")
print("nleku")
print("sfftb")
print("pmors")
print("toaoo")
print("drpui")
print("ohxin")
print("ofneq")
print("feqrd")
print("jbxoj")
print("kfuwn")
print("qbhfw")
print("fcbsk")
print("gcifv")
print("nugyj")
print("afarv")
print("arvxx")
print("risai")
print("ghnhy")
print("luvsu")
print("ibeip")
