import git
from git_contributions_importer import *


repo = git.Repo("P:/JIraBitBucket/ecos-scrape")
mock_repo = git.Repo("P:/FreeLance/mock-repo")

importer = Importer([repo], mock_repo)
importer.set_author(["amine.a.belgaid@gmail.com","amin-belgaid@hotmail.com"])

importer.import_repository()
print("duavj")
print("miijm")
print("xhhnf")
print("timer")
print("jagfg")
print("cqkna")
print("axyno")
print("bjqmo")
print("cvpij")
print("bvldc")
print("uyixr")
print("jwkoi")
print("wspje")
print("ofchp")
print("pfkxx")
print("ypwqw")
print("pdlrg")
print("mffbr")
print("nqewp")
print("yxcbn")
print("qevah")
print("xtooq")
print("henpi")
print("ycurj")
print("xbobq")
print("tyvhb")
print("hnfca")
print("slwkh")
print("qlcam")
print("gvsvt")
print("rvswu")
print("eyhdi")
print("ohvmw")
print("cqedw")
print("ruwtx")
print("xnxxt")
print("mojnm")
print("mnyxj")
print("dvudx")
print("ifmch")
print("xwdix")
print("ladyr")
print("rwrwk")
print("pugtn")
print("lfteu")
print("sxqck")
print("dwjes")
print("pibsi")
print("gvfae")
print("csrtj")
print("ypttr")
print("vmpie")
print("ihqwd")
print("lxumt")
print("swkcv")
print("slqcc")
print("slgme")
print("uliij")
print("tkatq")
print("phwuy")
print("honok")
print("kxiyc")
print("anpqg")
print("obfnf")
print("awbuj")
print("pfxsr")
print("takod")
print("ftqhb")
print("vhbhp")
print("siqlw")
print("mvwhd")
print("iwkno")
print("gagta")
print("pddcn")
print("imlov")
print("mvnog")
print("absuy")
print("uhjlr")
print("ewlcy")
print("orcxi")
print("gbfyd")
print("udbmn")
print("tjhyl")
